// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuL4G8J9Y1rcKQ4gPaaswXLX6ElMLUwuk',
    appId: '1:850741063556:web:e9395f3ae7cbd1fc0837d1',
    messagingSenderId: '850741063556',
    projectId: 'fire-safety-6370b',
    authDomain: 'fire-safety-6370b.firebaseapp.com',
    storageBucket: 'fire-safety-6370b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWNZiLVGSc3VaYusRXHmQAJO75jL6P808',
    appId: '1:850741063556:android:7f9b3e52bdaa86ec0837d1',
    messagingSenderId: '850741063556',
    projectId: 'fire-safety-6370b',
    storageBucket: 'fire-safety-6370b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDauOkbRP0EshQXziI4Q9owIJdSza41Pik',
    appId: '1:850741063556:ios:db4b703c80e493510837d1',
    messagingSenderId: '850741063556',
    projectId: 'fire-safety-6370b',
    storageBucket: 'fire-safety-6370b.firebasestorage.app',
    iosBundleId: 'com.example.fireSafetySuffolk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDauOkbRP0EshQXziI4Q9owIJdSza41Pik',
    appId: '1:850741063556:ios:db4b703c80e493510837d1',
    messagingSenderId: '850741063556',
    projectId: 'fire-safety-6370b',
    storageBucket: 'fire-safety-6370b.firebasestorage.app',
    iosBundleId: 'com.example.fireSafetySuffolk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuL4G8J9Y1rcKQ4gPaaswXLX6ElMLUwuk',
    appId: '1:850741063556:web:8e8e3515d5a3c2b60837d1',
    messagingSenderId: '850741063556',
    projectId: 'fire-safety-6370b',
    authDomain: 'fire-safety-6370b.firebaseapp.com',
    storageBucket: 'fire-safety-6370b.firebasestorage.app',
  );
}
